#8004表示注册到zookeeper服务器的支付服务提供者端口号
server:
  port: 80
#服务别名----注册zookeeper到注册中心名称
spring:
  application:
    name: springcloud-consumer-order
  cloud:
    zookeeper:
      connect-string: 39.106.163.62:2181
